### ISSUE TITLE
Is the WaveUNet code available?

### ISSUE THREAD

**Issue by dlphil** [LiQiufu/WaveCNet#1]
Thank you for publishing this paper and making your DWT and IDWT layer code available. I am interested in wavelet transforms and previously explored their use in CNNs for cloud detection (related [paper link](https://arxiv.org/abs/2007.13678)). I have begun testing your provided sample networks with low-frequency-only DWT downsampling. Would it be possible for you to also upload an example WaveUNet model showcasing how you performed the inverse transform? Thanks again!

**Comment by LiQiufu** [comment]
> Thank you for publishing this paper and making your DWT and IDWT layer code available. I am interested in wavelet transforms and previously explored their use in CNNs for cloud detection (related [paper link](https://arxiv.org/abs/2007.13678)). I have begun testing your provided sample networks with low-frequency-only DWT downsampling. Would it be possible for you to also upload an example WaveUNet model showcasing how you performed the inverse transform? Thanks again!

WaveUNet is renamed with WaveSNet. The code of Wavelet integrated U-Net and DeepLabV3+ are available in https://github.com/LiQiufu/WaveSNet

**Comment by dlphil** [comment]
Thank you again, @LiQiufu, for this research and code.
