### ISSUE TITLE
The code of Wavelet denoising block?

### ISSUE THREAD

**Issue by xyl-507** [LiQiufu/WaveCNet#10]
Dear author, thanks for your contribution.

 I'm interested in Soft Thresholding, so I want to know whether it is possible to publish the code of Wavelet denoising block?

Thanks in advance!

**Comment by LiQiufu** [comment]
The soft thresholding is implemented by applying torch.nn.Softshrink on the high-frequency component.

**Comment by xyl-507** [comment]
Thanks！

**Comment by xyl-507** [comment]
Thanks！
